server:
  port: 8766

spring:
  application:
    name: my-eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8766/eureka/
  server:
    enabled-self-preservation: true
    expected-client-renewal-interval-seconds: 30
    renewal-percent-threshold: 0.85
